# Generated by Django 3.2.9 on 2021-11-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.category'),
        ),
    ]
