# Generated by Django 3.2.9 on 2021-11-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellorder',
            name='item',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='money_used',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='seller',
            field=models.CharField(max_length=50),
        ),
    ]
